### ISSUE TITLE
Buffer feature does not draw correct distance

### ISSUE THREAD

**Issue by worknimble** [geomoose/geomoose#83] opened 2015-04-30 19:05 UTC
The buffer drawn is not the size of the input value entered. Example: draw a point and input 300 ft buffer, measure the diameter of the circle and is 180 ft diameter. Draw rectangle 550 ft x 550 ft and buffer 400 ft, result is rectangle 780 ft x 780 ft. 
Used other units of measure and all draw a smaller buffer than expected.

**Comment by theduckylittle** [comment] 2015-04-30 19:15
Can you verify that this distance is short by half?

There will *always* be a rounding error based on the resolution of the screen and the number of pixels per unit.  I created a 300 ft buffer of a point and measured nearly 300 ft (well within the resolutional tolerance) diameter around the point instead of 300 ft radius.

**Comment by theduckylittle** [comment] 2015-04-30 19:17
Ack, I can confirm it's not just by half (diameter vs. radius).

This is ostensibly a projection problem.

**Comment by klassenjs** [comment] 2015-04-30 19:19
That sure looks like a meters to feet conversion issue.

300' buffer = 600' diameter is being drawn as 180'.
600/180 ≈ 3937/1200.

**Comment by theduckylittle** [comment] 2015-04-30 19:23
I'm seeing the bug even with meters on meters.

**Comment by worknimble** [comment] 2015-04-30 19:36
I see this with inches, meters, feet, yards, mile, km. Pretty much looks like it is drawing about 60% of the value input for buffer.

**Comment by theduckylittle** [comment] 2015-05-08 16:10
I cannot find my commits on this one but there was a projection issue and it is now fixed.

**Closed** 2015-07-10 20:17 UTC
Labels: bug, review
